#!/usr/bin/env python3
"""Compare declared engineering-platform adoption against reality.

The registry declares which repos are expected to carry the platform conventions
(`platform: required`). Before it existed nothing did: membership was "the repo
happens to have a .ai-platform.json", discovered only when someone ran a check
inside that repo. Every platform document said eight repos; there were eleven.

For each declared repo this reports:

  missing-pin       no .ai-platform.json at all
  unknown-version   the pinned version is not a released tag
  behind            the pin is older than the newest release (minor/major = error)
  sync-mismatch     the pin and ai/shared/README.md disagree, i.e. the version was
                    bumped without re-running sync.sh -- nothing else detects this,
                    because that README is generated by sync, not a manifest entry
  no-conformance    no .github/workflows/ai-conformance.yml, so the repo's own
                    conformance gate never runs and its drift is invisible

and, in the other direction:

  undeclared        a repo carrying a pin that the registry calls exempt, or does
                    not list at all

    platform_drift.py [--format text|github|markdown]
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import registry as reg  # noqa: E402

ORG = "Innogando"
PLATFORM_REPO = "engineering-platform"
PIN_PATH = ".ai-platform.json"
SYNCED_PATH = "ai/shared/README.md"
CONFORMANCE_PATH = ".github/workflows/ai-conformance.yml"
SEMVER = re.compile(r"^v(\d+)\.(\d+)\.(\d+)$")
SYNCED_FROM = re.compile(r"Synced from:\s*engineering-platform\s+(v\d+\.\d+\.\d+)")


def gh(*args: str) -> tuple[int, str]:
    proc = subprocess.run(["gh", *args], capture_output=True, text=True)
    return proc.returncode, proc.stdout


def read_file(repo: str, path: str, ref: str | None = None) -> str | None:
    """Contents of `path`, from the repo's default branch unless `ref` says otherwise."""
    url = f"repos/{ORG}/{repo}/contents/{path}"
    if ref:
        url += f"?ref={ref}"
    code, out = gh("api", url, "--jq", ".content")
    if code != 0 or not out.strip():
        return None
    return base64.b64decode(out).decode("utf-8", "replace")


def pin_on(repo: str, ref: str) -> str | None:
    raw = read_file(repo, PIN_PATH, ref=ref)
    if raw is None:
        return None
    try:
        return json.loads(raw).get("version") or None
    except json.JSONDecodeError:
        return None


def released_versions() -> list[tuple[int, int, int]]:
    code, out = gh("api", f"repos/{ORG}/{PLATFORM_REPO}/tags", "--paginate", "--jq", ".[].name")
    if code != 0:
        raise RuntimeError("could not list engineering-platform tags")
    found = []
    for name in out.split():
        m = SEMVER.match(name)
        if m:  # excludes pre-release tags such as v0.9.0-test
            found.append(tuple(int(g) for g in m.groups()))
    return sorted(found, reverse=True)


def fmt(v: tuple[int, int, int]) -> str:
    return "v%d.%d.%d" % v


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default=reg.DEFAULT_PATH)
    ap.add_argument("--format", choices=("text", "github", "markdown"), default="text")
    args = ap.parse_args()

    registry = reg.load(args.registry)
    declared = set(reg.repos_requiring_platform(registry))
    latest = released_versions()[0]

    findings: list[tuple[str, str, str, str]] = []  # severity, repo, kind, detail

    def add(sev: str, repo: str, kind: str, detail: str) -> None:
        findings.append((sev, repo, kind, detail))

    rows = []
    for repo in sorted(declared):
        raw = read_file(repo, PIN_PATH)
        if raw is None:
            add("error", repo, "missing-pin", f"no {PIN_PATH}; declared platform: required")
            rows.append((repo, "-", "-", "-"))
            continue
        try:
            pin = json.loads(raw).get("version", "")
        except json.JSONDecodeError as exc:
            add("error", repo, "missing-pin", f"{PIN_PATH} is not valid JSON ({exc})")
            rows.append((repo, "invalid", "-", "-"))
            continue

        m = SEMVER.match(pin or "")
        if not m:
            add("error", repo, "unknown-version", f"pin {pin!r} is not a released tag")
            pin_t = None
        else:
            pin_t = tuple(int(g) for g in m.groups())
            if pin_t not in released_versions():
                add("error", repo, "unknown-version", f"pin {pin} has no matching tag")
            elif pin_t < latest:
                gap = "patch" if pin_t[:2] == latest[:2] else "minor/major"
                detail = f"pinned {pin}, released {fmt(latest)} ({gap} behind)"
                # A repo on a release train (rumi-app) upgrades on develop first, so
                # say so rather than reporting an upgrade that is merely unshipped.
                unshipped = pin_on(repo, "develop")
                if unshipped and unshipped != pin:
                    detail += f"; develop already carries {unshipped}, not yet shipped to the default branch"
                add("warning" if gap == "patch" else "error", repo, "behind", detail)

        synced_raw = read_file(repo, SYNCED_PATH)
        synced = None
        if synced_raw:
            sm = SYNCED_FROM.search(synced_raw)
            synced = sm.group(1) if sm else None
            if synced and pin and synced != pin:
                add(
                    "error", repo, "sync-mismatch",
                    f"pin says {pin} but {SYNCED_PATH} says {synced}: the version was "
                    f"bumped without re-running sync.sh",
                )

        has_conf = read_file(repo, CONFORMANCE_PATH) is not None
        if not has_conf:
            add(
                "error", repo, "no-conformance",
                f"no {CONFORMANCE_PATH}; this repo's own conformance gate never runs",
            )
        rows.append((repo, pin or "-", synced or "-", "yes" if has_conf else "NO"))

    # The other direction: adopters nobody declared.
    code, out = gh("repo", "list", ORG, "--limit", "500", "--json", "name,isArchived",
                   "--jq", ".[] | select(.isArchived == false) | .name")
    for repo in sorted(out.split()):
        if repo in declared or repo == PLATFORM_REPO:
            continue
        if read_file(repo, PIN_PATH) is None:
            continue
        cfg = reg.entry(registry, repo)
        how = "not in the registry" if cfg is None else f"declared platform: {cfg.get('platform')}"
        add("error", repo, "undeclared", f"carries {PIN_PATH} but is {how}")

    errors = [f for f in findings if f[0] == "error"]
    warnings = [f for f in findings if f[0] == "warning"]

    if args.format == "markdown":
        print(f"# Platform fleet\n")
        print(f"Newest release: **{fmt(latest)}**. "
              f"{len(declared)} repos declared `platform: required`.\n")
        print("| repo | pin | synced tree | conformance workflow |")
        print("|---|---|---|---|")
        for repo, pin, synced, conf in rows:
            print(f"| `{repo}` | {pin} | {synced} | {conf} |")
        print(f"\n## Findings\n")
        if not findings:
            print("None.")
        for sev, repo, kind, detail in findings:
            print(f"- **{sev}** `{repo}` *{kind}* — {detail}")
    else:
        print(f"newest release: {fmt(latest)} | declared: {len(declared)}")
        for sev, repo, kind, detail in findings:
            line = f"{repo}: {kind}: {detail}"
            print(f"::{sev}::{line}" if args.format == "github" else f"{sev.upper():<8}{line}")
        print()
        print(f"{len(errors)} error(s), {len(warnings)} warning(s)")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
